import './globals.css';
import Navbar from './components/Navbar';
import AuthContext from '../context/AuthContext';

export const metadata = {
  title: "CHUL'S instagram",
  description: 'Generated by create next app',
};

export default function RootLayout({ children, }: { children: React.ReactNode; }) {
  return (
    <html lang='en'>
      <body className='w-full max-w-screen-xl overflow-auto mx-auto'>
        <AuthContext>
          <header className='sticky top-0 bg-white z-10 border-b'>
            <Navbar />
          </header>
          <main>{children}</main>
        </AuthContext>
      </body>
    </html>
  );
}
